### ISSUE TITLE
conda-forge/neptune-client-feedstock stopped automerging with no apparent reason

### ISSUE THREAD

**Issue by PiotrJander** [conda-forge/neptune-client-feedstock#42]
cc @conda-forge/bot 

I am one of the maintainers of https://github.com/conda-forge/neptune-client-feedstock

Recently, as we bumped the version of neptune-client on PyPI from 0.5.x to 0.9.0, conda-forge bot stopped automerging new versions and publishing them on conda. We have had to publish those new version by making manual changes to https://github.com/conda-forge/neptune-client-feedstock .

Is this a problem with conda forge automerging mechanism or something we are missing as maintainers?

I am happy to provide more details, but not sure what info is relevant.

This issue it re-posted from https://github.com/conda-forge/conda-feedstock/issues/142 . I got the following piece of advice

>Also, if you go to https://conda-forge.org/status/#version_updates and search for your package you'll probably see a log of the bot error.

but I can't see anything related to neptune-client on that page.

**Comment by beckermr** [comment]
The way your package is being versioned is causing the bot to not be able to discover new versions via the url or for it to think the version is not valid. Specifically the "client/0.9.5" tags are likely confusing it.

**Comment by PiotrJander** [comment]
Hi @beckermr , thanks for the quick reply.

Are there any docs describing the version format expected by the bot? I couldn't find any such docs. Does the bot look at Git tags in the package repo, or does it look at versions published to PyPI?

If it is at all relevant, our use case for this particular versioning scheme is to prepare different packages from the same repo.
And so e.g. `client/x.x.x` tags produce new versions of the `neptune-client` package, `pytorch/x.x.x` tags produce new versions of `neptune-pytorch` package etc. Is it at all possible to make conda bot work with this scheme? Or would you recommend any other scheme which addresses our use case and it compatible with conda?

**Comment by beckermr** [comment]
The bot expects versions in the form supported by conda. See the conda documentation.

**Comment by PiotrJander** [comment]
Just for the record, I found some docs about what version formats conda expects:

- https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#supported-version-strings
- https://www.python.org/dev/peps/pep-0440/

But it is not specified anywhere that Git tags used in the repo have any meaning to Pip or to conda.

So @beckermr I wonder if we could confirm that the conda bot does indeed look at Git tags in the package repo as opposed to versions published to PyPI. If this is the case, then perhaps this should be made explicit in the Conda Forge docs somewhere.

Also

> The way your package is being versioned is causing the bot to not be able to discover new versions via the url or for it to think the version is not valid. Specifically the "client/0.9.5" tags are likely confusing it.

could you point me to some docs describing in more detail for the Conda bot discovers new versions? This could help us adjust our repo tagging scheme to be compatible with Conda.

**Comment by beckermr** [comment]
To adjust the scheme, simply make each tag a simple version number. You won't be able to release more than one project per repo.

**Comment by PiotrJander** [comment]
@conda-forge/bot I'd like to report that even though Neptune has changed its tagging scheme to "x.y.z" versions (see https://github.com/neptune-ai/neptune-client/tags) , Conda Forge bot still doesn't discover new versions automatically, like described above. We'll need help fixing this as we're not sure how to debug Conda Forge bot's behaviour.

**Comment by beckermr** [comment]
We may need to change some of the bot metadata to get it going again. Please make an issue on regro/cf-scripts and I will try and get to it today.

**Comment by PiotrJander** [comment]
Thanks for your help, but just letting you know that the bot has not opened a new PR in neptune-client-feedstock, so it doesn't seem like this solved the problem.

**Comment by beckermr** [comment]
See the status page. The recipe has an error in it that is causing a failure, per the error message there. The bot itself found the version since it produced that error.

also, the build on master is failing due to a sha mismatch, which may be related: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=314469&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by isuruf** [comment]
Also please use PRs (from forks) instead of directly committing to master.

**Comment by beckermr** [comment]
Also, I think the old versions in the feed are confusing the bot. Right now it has a version starting with `2F` which is part of an HTML encoding of a `/` maybe?

**Comment by PiotrJander** [comment]
Thanks, I did correct the SHA of the newest version - thanks for pointing this out. We'll avoid pushing directly to master from now on.

Regarding those malformed versions with `2F` at the start - I assume there is nothing we can do as maintainers so we'll just wait for the bot to reset.

**Comment by PiotrJander** [comment]
Fantastic, thanks a lot!
